### ISSUE TITLE
org.sqlite.JDBC error

### ISSUE THREAD

**Issue by pwnedDesal** [righettod/log-requests-to-sqlite#25]
I build the repository using gradle then when I use the produced .jar this error occurred .
![image](https://user-images.githubusercontent.com/6646675/100355303-76842c80-302c-11eb-9278-5e67a1474c62.png)

**Comment by righettod** [comment]
Hi,

Thank for the issue, do you have the same issue with the [night build](https://github.com/righettod/log-requests-to-sqlite/actions/runs/384637625) corresponding to your JDK.

I ask in order to identify if the issue is related to the source.

Thank a log for your feedback.

**Comment by pwnedDesal** [comment]
I have tried NightBuild-JDK-14.zip. it seems fine. no error at all. 
for JDK i used openjdk-15 to build the .jar file.  when I use Project SDK 1.8 I got `Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.`
![image](https://user-images.githubusercontent.com/6646675/100361259-e8607400-3034-11eb-9a19-87fe1b7a842e.png)

**Comment by righettod** [comment]
The project need at minimum the **OpenJDK 11** due to [this](https://github.com/righettod/log-requests-to-sqlite/issues/15#issuecomment-643103593).

I will try to see if the **OpenJDK 15** is available in GH actions and add it the build pipeline matrix in order to check if the current sources are OK with this version of the JDK.

Are you unlocked with the night build?

**Comment by righettod** [comment]
Night build [for JDK 15](https://github.com/righettod/log-requests-to-sqlite/actions/runs/385395199) is OK 😃
