### ISSUE TITLE
Can't log HTTP response

### ISSUE THREAD

**Issue by pwnedDesal** [righettod/log-requests-to-sqlite#26]
I am trying to log the HTTP response as well using **messageInfo.getResponse()**. I did some modification on the source code such as the SQL statements and on the **logEvent** method of ActivityLogger.java. The source code successfully compiled, but at the time **the log-request-to-sqlite** logs the HTTP request and response I always get this error.

```
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Data cannot be null
	at burp.en1.bytesToString(Unknown Source)
	at burp.drp.bytesToString(Unknown Source)
	at burp.ActivityLogger.logEvent(ActivityLogger.java:114)
	at burp.ActivityHttpListener.processHttpMessage(ActivityHttpListener.java:47)
```
looks like the HTTP response is not available yet at the time of logging. is there a way to detect when the HTTP response is available?
P.S. 
Sorry, This 🥔 is not good at Java.
![1](https://user-images.githubusercontent.com/6646675/100415430-14bcd480-30b7-11eb-9868-7c367d896592.png)
![2](https://user-images.githubusercontent.com/6646675/100415433-17b7c500-30b7-11eb-999f-6cecbec2ccdc.png)

**Comment by righettod** [comment]
Hi,

In fact you need to log the response only when the following flag is **false** because it indicate if the current object is a **request**:

![image](https://user-images.githubusercontent.com/1573775/100426243-d44a6000-3090-11eb-9239-662fa76443e5.png)

Class javadoc documentation:

![image](https://user-images.githubusercontent.com/1573775/100426477-360aca00-3091-11eb-8bca-05e6c8997313.png)

**Comment by pwnedDesal** [comment]
lol I did see that hahahaha 🤦thank you

**Comment by righettod** [comment]
You can also look at the [piper](https://portswigger.net/bappstore/e4e0f6c4f0274754917dcb5f4937bb9e) burp extension if you need to work with request/response for processing that burp do not support out of the box.
