### ISSUE TITLE
can you support mysql

### ISSUE THREAD

**Issue by feeops** [righettod/log-requests-to-sqlite#60]
can you support mysql?

**Comment by righettod** [comment]
Hi,

It is not planned because the goal of the extension is the have a portable store to be able to give it to a client after an assessment. 

However, you can easily fork the repo and create a version of the extension storing data into MySQL via the following steps:
1. Add the MySQL driver to the **pom.xml** file.
2. Adapt the connection handler for MySQL, [here](https://github.com/righettod/log-requests-to-sqlite/blob/master/src/burp/ActivityLogger.java#L70) and [here](https://github.com/righettod/log-requests-to-sqlite/blob/master/src/burp/ActivityLogger.java#L84).
3. Perhaps adapt SQL query [here](https://github.com/righettod/log-requests-to-sqlite/blob/master/src/burp/ActivityLogger.java#L21) if needed according to MySQL support for some functions used.

That's all update needed 😃
