### ISSUE TITLE
Add the ability to pause the logging

### ISSUE THREAD

**Issue by Mincka** [righettod/log-requests-to-sqlite#9]
Would it be possible to add an option in the menu to pause the logging (and remember this decision between sessions)?

And also give this option in the pop-up window on startup?

It could be by having a third button to pause the logging.
![image](https://user-images.githubusercontent.com/6184289/63322223-27c4ee80-c323-11e9-842f-b7f9908d8c30.png)

I don't always need to log the requests and I don't want to unload the extension.

Thank you. 😄

**Comment by righettod** [comment]
New menu added from the Burp main screen:

![image](https://user-images.githubusercontent.com/1573775/63648048-37c93d80-c72a-11e9-9648-9cdee22acc97.png)

Refactored menu when Burp is started and the logging was not previously paused (otherwise no question is asked):

![image](https://user-images.githubusercontent.com/1573775/63648064-719a4400-c72a-11e9-92cd-969cecaa15eb.png)

When logging is re-enabled then the Db file configured prior to the pausing is used.

**Comment by righettod** [comment]
Published in this [Beta release](https://github.com/righettod/log-requests-to-sqlite/releases/tag/v1.0.8-beta).
